
CREATE TABLE IF NOT EXISTS leads(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT,
email TEXT,
service TEXT,
budget TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
client TEXT,
service TEXT,
amount INTEGER,
status TEXT
);

CREATE TABLE IF NOT EXISTS payments(
id INTEGER PRIMARY KEY AUTOINCREMENT,
client TEXT,
amount INTEGER,
status TEXT
);

CREATE TABLE IF NOT EXISTS promotions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
platform TEXT,
topic TEXT,
status TEXT
);
